# Build on multiple platforms - https://docs.microsoft.com/azure/devops/pipelines/get-started-multiplatform?view=azure-devops&WT.mc_id=devops-github-shboyer
strategy:
  matrix:
    linux:
      displayName: 'Linux Build'
      imageName: 'ubuntu-16.04'
    mac:
      displayName: 'MacOS Build'
      imageName: 'macos-10.13'
    windows:
      displayName: 'Windows Build'      
      imageName: 'windows-2019'

pool:
  vmImage: $(imageName)
#  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.2.100'

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '2.1.500'

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '**/*.sln'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.sln'
    arguments: '--configuration Release'